const Url = {
  login: 'user/login',
  logout: 'user/logout',
  getUserInfo: 'user/userInfo',
  createUser: 'user/register',
  regions: 'filter/regions',
  home: 'news/home',
  listService: 'service/list',
  serviceDetail: 'service/detail',
  review: 'service/review',
  createOrder: 'order/create-order',
  listOrder: 'order/list-order-history',
  orderDetail: 'order//order-detail',
  updateTransaction: 'order/update-transaction',
  orderCustomer: 'order/orderCustomer',
  customerUpdate: 'user/updateMe',
  uploadAvatar: 'user/uploadAvatar',
  userReferred: 'user/referred',
  updateIsRead: 'user/updateIsRead',
  createNoti: 'user/createNoti',
  forgotPassword: 'user/forgotPassword',
  listCate: 'service_category/list',
  newDetail: 'news/newsDetail',
  likeService: 'service/likeService',
  listServiceLiked: 'service/listServiceLiked',
  orderReview: 'order/review',
  transactionDetail: 'order/transactionDetail',
  getListNotif: 'user/getlistNoti',
  createOrderCustomer: 'order/orderCustomerV2',
  deleteOrderCustomer: 'order/deleteOrderCustomer',
  requestPament: 'order/requestPament',
  changePassword: 'user/changePassword',
  getConfig: 'user/getConfig',
  listCustomer: 'user/list',
  deleteCustomer: 'user/delete',
  deleteCategory: 'service_category/delete',
  categoryDetail: 'service_category/detail',
  updateCategory: 'service_category/update',
  createCategory: 'service_category/create',
  updateService: 'service/update',
  createService: 'service/create',
  listOrderCustomer: 'order/list-order',
  orderCustomerDetail: 'order/order-detail',
  updateOrder: 'order/update-order',
}

export default Url
